<section class="black">
	<div class="inner-container">
		<div class="intro"> 
			<h2 class="heading">Privacy Policy</h2>
		</div>
	</div>
</section>
<section class="white">
	<a id="privacy" class="anchor"></a>
	<div class="inner-container">		 
		<div class="row">
			<div class="col s12">				
				<h4>How We Collect and Use Information</h4>

				<h5>We collect the following types of information about you:</h5>
				<p><strong>Analytics information:</strong> We may directly collect analytics data, or use third-party analytics tools and services, to help us measure traffic and usage trends for the Website. These tools collect information sent by your browser or mobile device, including the pages you visit and other information that assists us in improving the Website. We collect and use this analytics information in aggregate form such that it cannot reasonably be manipulated to identify any particular individual user.</p>

				<p><strong>Cookies information:</strong> Full details can be found on our Cookie Policy. When you visit the Website, we may send one or more cookies — a small text file containing a string of alphanumeric characters — to your computer that uniquely identifies your browser and lets FrankenSkiestheMovie help you log in faster and enhance your navigation through the site. A cookie may also convey information to us about how you use the Website (e.g., the pages you view, the links you click and other actions you take on the Website), and allow us or our business partners to track your usage of the Website over time. A persistent cookie remains on your hard drive after you close your browser. Persistent cookies may be used by your browser on subsequent visits to the site. Persistent cookies can be removed by following your web browser’s directions. A session cookie is temporary and disappears after you close your browser. You can reset your web browser to refuse all cookies or to indicate when a cookie is being sent. However, some features of the Website may not function properly if the ability to accept cookies is disabled. Full details can be found on our Cookie Policy.</p>

				<p><strong>Log file information:</strong> Log file information is automatically reported by your browser or mobile device each time you access the Website. When you use our Website, our servers automatically record certain log file information. These server logs may include anonymous information such as your web request, Internet Protocol (“IP”) address, browser type, referring / exit pages and URLs, number of clicks and how you interact with links on the Website, domain names, landing pages, pages viewed, and other such information.</p>

				<p><strong>Clear gifs/web beacons information:</strong> When you use the Website, we may employ clear gifs (also known as web beacons) which are used to anonymously track the online usage patterns of our Users. In addition, we may also use clear gifs in HTML-based emails sent to our users to track which emails are opened and which links are clicked by recipients. The information is allows for more accurate reporting and improvement of the Website.</p>
<!-- 
				<h6>Device identifiers:</h6>
				<p>When you access the Website by or through a mobile device (including but not limited to smart-phones or tablets), we may access, collect, monitor and/or remotely store one or more “device identifiers,” such as a universally unique identifier (“UUID”). Device identifiers are small data files or similar data structures stored on or associated with your mobile device, which uniquely identify your mobile device. A device identifier may be data stored in connection with the device hardware, data stored in connection with the device’s operating system or other software, or data sent to the device by FrankenSkiestheMovie. A device identifier may convey information to us about how you browse and use the Website. A device identifier may remain persistently on your device, to help you log in faster and enhance your navigation through the Website. Some features of the Website may not function properly if use or availability of device identifiers is impaired or disabled.</p> -->

				<!-- <h6>Location data:</h6>
				<p>When you access the Website by or through a mobile device, we may access, collect, monitor and/or remotely store “location data,” which may include GPS coordinates (e.g. latitude and/or longitude) or similar information regarding the location of your mobile device. Location data may convey to us information about how you browse and use the Website. Some features of the Website, particularly location-based services, may not function properly if use or availability of location data is impaired or disabled.</p> -->

				<!-- <h6>Commercial and marketing communications:</h6>
				<p>We use the information we collect or receive, such as your email address, to communicate directly with you. We may send you emails containing newsletters, promotions, and special offers. If you do not want to receive such email messages, you will be given the option to opt out or change your preferences. We also use your information to send you Website-related emails (e.g., account verification, purchase and billing confirmations and reminders, changes/updates to features of the Website, technical and security notices). You may not opt out of Website-related emails. You may also be able to be “found” on FrankenSkiestheMovie based on information that you provide (see “Find friends on FrankenSkiestheMovie”) above.</p> -->

				<p><strong>Use of certain service type information we collect about you:</strong> We use or may use cookies, log file, device identifiers, location data and clear gifs information to: (a) remember information so that you will not have to re-enter it during your visit or the next time you visit the site; (b) provide custom, personalized content and information; (c) to provide and monitor the effectiveness of our Website; (d) monitor aggregate metrics such as total number of visitors, traffic, and demographic patterns; (e) diagnose or fix technology problems; (f) help you efficiently access your information after you sign in; (g) to provide advertising to your browser or device, and (h) automatically update the FrankenSkiestheMovie application on your mobile devices.</p>


				<h6>Sharing of Your Information</h6>
				<p>We will not rent or sell your information into third parties outside FrankenSkiestheMovie and its group companies (including any parent, subsidiaries and affiliates) without your consent, except as noted below:</p>

				<p><strong>Who we may share your information with:</strong> We may share your information with third-party business partners and Trusted Users for the purpose of providing the Website to you. Third party business partners will be given limited access to your information as is reasonably necessary to deliver the Website, and we will require that such third parties comply with this Privacy Policy, or operate under a similar privacy policy.</p>

				<!-- <p>Who can see User Content:<p>
				<p>Any User Content that you voluntarily disclose for posting to the Website becomes available to the public and cannot be removed, except by FrankenSkiestheMovie in its sole discretion. Once posted on FrankenSkiestheMovie, User Content may not be removable from public view, as copies may remain viewable in cached and archived pages of the Website, on other sites that have republished us, or if other Users have copied or saved that information. If you do not wish your User Content to be available to the public, please don’t post it on FrankenSkiestheMovie. Your username and if you choose to disclose it, your real name, will be published publicly. Once published your username and / or real name may not be able to be removed.</p>

				<p>Who can see your IP address: If you post User Content on the Website while not logged in, your IP address will be published with your User Content in order to attribute your contribution to the Website. A selection of Trusted Users with administrative powers on FrankenSkiestheMovie have the ability to review IP addresses of users to reduce abusive behavior. Any third party service embedded on FrankenSkiestheMovie such as an advertiser, video provider, social network or other third party will also have access to your IP address.</p>

				<p>Who can see your email address: If you enter an email address, you will enable communication from FrankenSkiestheMovie and other Users. If you reply to users or participate in group FrankenSkiestheMovie activities such as meetups, your email address will be shared with these users. In addition, some email addresses such as blocked@FrankenSkiestheMovie.com forward to a group of Trusted Users, who will use your email address to reply to the email.</p>
 -->
				<!-- <h6>What happens in the event of a change of control:</h6>
				<p>We may buy or sell/divest/transfer the company (including any shares in the company), or any combination of its products, services, assets and/or businesses. Your information such as customer names and email addresses, User Content and other user information related to the Website may be among the items sold or otherwise transferred in these types of transactions. We may also sell, assign or otherwise transfer such information in the course of corporate divestitures, mergers, acquisitions, bankruptcies, dissolutions, reorganizations, liquidations, similar transactions or proceedings involving all or a portion of the company.</p> -->

				<p><strong>Instances where we are required to share your information:</strong> FrankenSkiestheMovie will disclose your information where required to do so by law or subpoena or if we reasonably believe that such action is necessary to (a) comply with the law and the reasonable requests of law enforcement; (b) to enforce our Terms of Use or to protect the security, quality or integrity of our Website; and/or (c) to exercise or protect the rights, property, or personal safety of FrankenSkiestheMovie, our Users, or others.</p>

				<!-- <h6>Ads on FrankenSkiestheMovie:</h6>
				<p>We may also share certain information such as your location, browser, and cookie data and other data relating to your use of our Website with our business partners to deliver advertisements (“ads”) that may be of interest to you. FrankenSkiestheMovie may allow third-party ad servers or ad networks to serve advertisements on the Website. These third-party ad servers or ad networks use technology to send, directly to your browser or mobile device, the ads and ad links that appear on the Website, and will automatically receive your IP address when they do so. They may also use other technologies (such as cookies, JavaScript, device identifiers, location data, and clear gifs, see above) to compile information about your browser’s or device’s visits and usage patterns on the Website and on other websites, and to measure the effectiveness of their ads and to personalize the advertising content delivered to you.</p>

				<p>For example, Google uses DART cookies in order to deliver ads to you through the Website. Google's use of the DART cookie enables it and its partners to serve ads to you based on your visit to the Website and previous websites that you may have visited. Other advertising networks also use similar cookies, clear gifs, or other mechanisms to deliver targeted advertising to you through the Website. You can delete these cookies by following the instructions here: http://www.FrankenSkiestheMovie.com/Clear-Your-Browser%27s-Cookies . You may opt out of use of Google’s DART cookie and cookies placed by Network Advertising Initiative (NAI) certified ad networks here: http://www.networkadvertising.org/managing/opt_out.asp . Opting out of these cookies will be effective not only on the Website, but on all websites with NAI certified advertising networks. However, these opt-outs will be ineffective on networks that are not NAI certified.</p> -->

				<!-- <p>Please note that an advertiser may ask FrankenSkiestheMovie to show an ad to a certain audience of Users (e.g., based on demographics or other interests). In that situation, FrankenSkiestheMovie or our Partners determines the target audience and FrankenSkiestheMovie serves the advertising to that audience and only provides anonymous data to the advertiser. If you respond to such an ad, the advertiser or ad server may conclude that you fit the description of the audience they are trying to reach.</p> -->

				<p>To enhance your user experience or help us improve and measure our effectiveness, FrankenSkiestheMovie may embed code from third parties on the Website. Examples of such parties may include Facebook, Twitter, Pinterest, Google, YouTube, Howcast, VideoJug, AOL, and others. These third parties may collect information about you including IP address, cookies in ways FrankenSkiestheMovie does not control.</p>

				<p>The FrankenSkiestheMovie Privacy Policy does not apply to, and we cannot control the activities of third-parties. Please consult the respective privacy policies of such third parties or contact such third parties for more information.</p>

				<p><strong>Opting out of collection of your information for Tracking / Advertising:</strong> Please refer to your mobile device or browser’s technical information for instructions on how to delete and disable cookies, and other tracking/recording tools. Depending on your type of device, it may not be possible to delete or disable tracking mechanisms on your mobile device. Note that disabling cookies and/or other tracking tools prevents FrankenSkiestheMovie or its business partners from tracking your browser’s activities in relation to the Website, and for use in targeted advertising activities by third parties. However, doing so may disable many of the features available through the Website. If you have any questions about opting out of the collection of cookies and other tracking/recording tools, you can contact us directly at info@FrankenSkiestheMovie.com.</p>


				<h6>Children’s Privacy</h6>
				<p>FrankenSkiestheMovie does not knowingly collect or solicit any information from anyone under the age of 13 or knowingly allow such persons to register as Users. The Website and its content are not directed at children under the age of 13. In the event that we learn that we have collected personal information from a child under age 13 without verification of parental consent, we will delete that information as quickly as possible. If you believe that we might have any information from or about a child under 13, please contact us at wiki@FrankenSkiestheMovie.com.</p>

				<h6>Links to Other Websites and Websites</h6>
				<p>We are not responsible for the practices employed by websites or services linked to or from the Website, including the information or content contained therein. Please remember that when you use a link to go from the Website to another website, our Privacy Policy does not apply to third-party websites or services. Your browsing and interaction on any third-party website or service, including those that have a link or advertisement on our website, are subject to that third party’s own rules and policies. In addition, you agree that we are not responsible and we do not control over any third-parties that you authorize to access your User Content. If you are using a third-party website or service (like Facebook, Google groups, or an IRC chatroom) and you allow such a third-party access to you User Content you do so at your own risk. This Privacy Policy does not apply to information we collect by other means (including offline) or from other sources other than through the FrankenSkiesthemovie.</p>		
			</div>			 
		</div>	
	</div>
</section>

